
services:
  network-install:
    image: teng2/irix-network-install:0.0.1
    # volumes:
    #   - irix:/irix
    network_mode: host
    hostname: irix
    tty: true 
    privileged: true 
    extra_hosts:
     - iris:192.168.9.1

  # irix-network-install-cient:
  #   image: sgi
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - irix:/irix
  #   networks:
  #     - irix

# volumes:
#   irix:
# networks:
#   irix:


