
services:
  irix:
    image: silicon

    # volumes:
    #   - irix:/irix
    network_mode: host
    tty: true 
    privileged: true 

  # irix-network-install-cient:
  #   image: sgi
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - irix:/irix
  #   networks:
  #     - irix

# volumes:
#   irix:
# networks:
#   irix:


