
FROM alpine:3.21

ARG ARCH=amd64
# may need rsh-redone 
RUN apk update && apk add --no-cache \
  supervisor \
  openssh \
  bash \
  kea \
  dnsmasq

#  (default is amd64)
ENV TFTP_NOW_VERSION=1.0.5
ENV TFTP_NOW_URL=https://github.com/puhitaku/tftp-now/releases/download/${TFTP_NOW_VERSION}/tftp-now-linux-${ARCH}

# Download and set up the binary
RUN wget -O  /bin/tftp-now ${TFTP_NOW_URL} && \
    chmod +x /bin/tftp-now

# VOLUME /tftpboot
EXPOSE 69/udp 
# add user tftp
# RUN addgroup -g $GID -S tftp && \
#     adduser --disabled-password --gecos "" --shell /sbin/nologin \
#             --home /home/tftp --no-create-home --ingroup tftp \
#             --uid $UID tftp

# COPY src/forward-stdout  etc/socklog.rules/forward-stdout
RUN echo 'IRIS:ip=192.168.9.1' > /etc/bootptab
COPY src/hosts /etc/hosts
COPY src/supervisord.conf /etc/supervisord.conf
USER root
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]