# Dockerfile
FROM docker.io/library/debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  net-tools \
  man \
  bash \
  tftpd-hpa \
  kea \
  dnsmasq \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean
USER root

# RUN apt-get update \
#  && </dev/null DEBIAN_FRONTEND=noninteractive \
#     apt-get --yes install --no-install-recommends git cmake build-essential cron \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*

# FROM ubuntu:16.04
# RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
# RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
# RUN DEBIAN_FRONTEND=noninteractive \
#   apt-get update && \
#   apt-get install -y \
#   python3 \
#   build-essential \
#   # tftpd \
#   tftp \
#   # rsh-redone-server \
#   mksh \
#   screen \
#   && rm -rf /var/lib/apt/lists/*
# RUN useradd -ms /bin/bash apprunner
# USER apprunner
